### PR TITLE
Adds config files for Grove Hat

### LINKED ISSUE #15: Support for Grove ADC on Basic Power Monitoring
Upgrading a demonstrator from PowerMonitoringBasic to PowerMonitoring. Single phase. 

PowerMonitoringBasic was working. PowerMonitoring did not. 

I'm using the Grove ADC. The traceback was:
```
2024-04-22T15:10:22.048915+01:00 DemoRailPowerBasic docker-current-sensing[1176]: ERROR:core.sensing_stack:Error during sampling: Traceback (most recent call>
2024-04-22T15:10:22.049002+01:00 DemoRailPowerBasic docker-current-sensing[1176]:   File "/app/core/sensing_stack.py", line 25, in execute
2024-04-22T15:10:22.049088+01:00 DemoRailPowerBasic docker-current-sensing[1176]:     sample_resp = self.device.sample()
2024-04-22T15:10:22.049169+01:00 DemoRailPowerBasic docker-current-sensing[1176]:   File "/app/core/device_modules/adc_grove.py", line 41, in sample
2024-04-22T15:10:22.049248+01:00 DemoRailPowerBasic docker-current-sensing[1176]:     raise e
2024-04-22T15:10:22.049356+01:00 DemoRailPowerBasic docker-current-sensing[1176]:   File "/app/core/device_modules/adc_grove.py", line 34, in sample
2024-04-22T15:10:22.049446+01:00 DemoRailPowerBasic docker-current-sensing[1176]:     readings = self.i2c.read_register(register_addr, 2,stop=True)
2024-04-22T15:10:22.049505+01:00 DemoRailPowerBasic docker-current-sensing[1176]:   File "/app/core/interface_modules/i2c.py", line 25, in read_register
2024-04-22T15:10:22.049570+01:00 DemoRailPowerBasic docker-current-sensing[1176]:     self.i2c.i2c_rdwr(write_reg_addr)
2024-04-22T15:10:22.049635+01:00 DemoRailPowerBasic docker-current-sensing[1176]:   File "/usr/local/lib/python3.9/site-packages/smbus2/smbus2.py", line 658,>
2024-04-22T15:10:22.049700+01:00 DemoRailPowerBasic docker-current-sensing[1176]:     ioctl(self.fd, I2C_RDWR, ioctl_data)
2024-04-22T15:10:22.049763+01:00 DemoRailPowerBasic docker-current-sensing[1176]: OSError: [Errno 5] Input/output error

```
Which looks similar to hardware disconnected, but `i2cdetect -y 1` reports the adc at 0x08 as expected. Switched back to PowerMonitoringBasic (master) and it's fine again. What broke? 

I am suspicious of the hardcoded address in the config file: https://github.com/DigitalShoestringSolutions/PowerMonitoring/blob/4b6625a0f690af022bf046d64f5f9e161e9ff84a/current_sensing/config/pm_b_1p.toml#L7

But shouldn't what address to poll be taken care of by the adc board selected: https://github.com/DigitalShoestringSolutions/PowerMonitoring/blob/4b6625a0f690af022bf046d64f5f9e161e9ff84a/current_sensing/config/pm_b_1p.toml#L20

So why is any address hardcoded?

### PR DESCRIPTION
**Pull request by Greg-Hawkridge**
fixes #15

### CODE REVIEW

**Comment by tobyaharris** [comment]
What's the thinking behind the default ADC channels? For BCR it's always 0 (then 2,4 for 3pu). For Grove it's 3 for single clamps then 0,2,4 for 3pu.

**Comment by Greg-Hawkridge** [comment]
Those were probably just what I used last time I tested. They don't really matter since they're overwritten in user config.

**Comment by tobyaharris** [comment]
If you have some clamp amplifiers, we can test this

**Review by tobyaharris — COMMENTED** [review]
Somewhat outside the remit of this PR, but while you're editing the interface modules - is there any reason 3ph BCR needs to define a spi1 interface? spi0 seems enough.

**Comment by tobyaharris** [comment]
Where does the Grove I2C address get defined? It looks like it's in https://github.com/DigitalShoestringSolutions/PowerMonitoring/blob/0f2f966b62966fb770fc80df925fda6a1b72e545/current_sensing/code/core/device_modules/adc_grove.py#L12
I presume these HATs are not stackable / there is no way to configure the address.

**Review by tobyaharris — APPROVED** [review]
It's certainly a lot better than both what's in `dev` at the moment and #30 . If you're happy with my changes, merge away.

**Comment by tobyaharris** [comment]
Tested on a pi4 4gb with BCR. Build time 459s. First start time 149s. 1p, 3pb, 3pu all behave as expected. 

Tested on a pi4 2gb Grove. Build time 496s. Start time 158s. Didn't work, dismissing my pre-emptive earlier approval.

**Comment by tobyaharris** [comment]
```
current-sensing-1      | ERROR:core.sensing_stack:Error during sampling: Traceback (most recent call last):
current-sensing-1      |   File "/app/core/sensing_stack.py", line 25, in execute
current-sensing-1      |     sample_resp = self.device.sample()
current-sensing-1      |   File "/app/core/device_modules/adc_grove.py", line 42, in sample
current-sensing-1      |     raise e
current-sensing-1      |   File "/app/core/device_modules/adc_grove.py", line 35, in sample
current-sensing-1      |     readings = self.i2c.read_register(self.i2c_address,register_addr, 2,stop=True)
current-sensing-1      |   File "/app/core/interface_modules/i2c.py", line 20, in read_register
current-sensing-1      |     write_reg_addr = Msg.write(address,[register])
current-sensing-1      |   File "/usr/local/lib/python3.9/site-packages/smbus2/smbus2.py", line 228, in write
current-sensing-1      |     return i2c_msg(
current-sensing-1      | TypeError: an integer is required (got type str)
```

**Comment by tobyaharris** [comment]
soon to be tested again

**Comment by tobyaharris** [comment]
This works at last. All grove configs (pm_b_1p_grove.toml, pm_b_3pb_grove.toml, pm_b_3pu_grove.toml) work as expected. The values are scaled correctly. The removal of old power calculations has not affected the deployment with the BCR ADC.

**Review by tobyaharris — DISMISSED** [review]
Tested & working

**Comment by tobyaharris** [comment]
Since some files were created and some copied, I've made the presence of execution bits consistent, by removing them all. I don't see why any of these config files need any. Restested on BCR 3pu, unaffected.

**Review by tobyaharris — APPROVED** [review]

**Pull request merged**
