### PR TITLE
Update pm_a_3p.toml

### PR DESCRIPTION
**Pull request by Greg-Hawkridge**
Addresses #13
to meet new config format

### CODE REVIEW

**Comment by Greg-Hawkridge** [comment]
@tobyaharris All working now

**Comment by tobyaharris** [comment]
@Greg-Hawkridge which hardware did you test it on?

**Comment by tobyaharris** [comment]
Of course I've since tested this branch on Table 1. Build time 553s. The sensing module seems happy running in advanced 3ph mode, but the pi is running so slowly that in half an hour it hasn't managed to cough up the docker logs. 

However I must add as I tested on a 2gb pi (`vcgencmd get_config total_mem`) the Grafana and Influx web interfaces were totally unusuable. SSH keeps timing out. The grafana dashboard has been loading for over half an hour and still hasn't got a single data point. See https://github.com/DigitalShoestringSolutions/PowerMonitoring/issues/17.

**Comment by tobyaharris** [comment]
I'd like to approve this - I thought I already had - but I've lost the approve button. All I'm offered is:
 `Merge without waiting for requirements to be met (bypass branch protections)`, 
But as you authored the PR and all the commits therein it should be easy to approve it properly.

**Review by tobyaharris — COMMENTED** [review]
Only thought is the default module config file selected in user_config. I'm tempted to say it should be none of them - to ensure the user has edited the config file to confirm all the choices therein. Does it handle this gracefully? - Mostly, see below.

It's happened that we once tested a basic setup, thought it was working but in fact it was just the simulator. The same will happen to a user before too long.

**Comment by tobyaharris** [comment]
Testing what happens if all module config files are commented out: 
```
current-sensing-1  | INFO:config:Loaded config file "./config/user_config.toml" specified in default
current-sensing-1  | CRITICAL:config:Config File Not Found - unable to load config file "./config/module_config.toml" specified by default.
current-sensing-1  | INFO:config:Loaded config file "./config/user_config.toml" specified in default
current-sensing-1  | CRITICAL:config:Config File Not Found - unable to load config file "./config/module_config.toml" specified by default.
current-sensing-1  | INFO:config:Loaded config file "./config/user_config.toml" specified in default
current-sensing-1  | CRITICAL:config:Config File Not Found - unable to load config file "./config/module_config.toml" specified by default.
current-sensing-1  | INFO:config:Loaded config file "./config/user_config.toml" specified in default
current-sensing-1  | CRITICAL:config:Config File Not Found - unable to load config file "./config/module_config.toml" specified by default.
current-sensing-1  | INFO:config:Loaded config file "./config/user_config.toml" specified in default
current-sensing-1  | CRITICAL:config:Config File Not Found - unable to load config file "./config/module_config.toml" specified by default.
current-sensing-1  | INFO:config:Loaded config file "./config/user_config.toml" specified in default
current-sensing-1  | CRITICAL:config:Config File Not Found - unable to load config file "./config/module_config.toml" specified by default.
current-sensing-1  | INFO:config:Loaded config file "./config/user_config.toml" specified in default
current-sensing-1  | CRITICAL:config:Config File Not Found - unable to load config file "./config/module_config.toml" specified by default.
current-sensing-1  | INFO:config:Loaded config file "./config/user_config.toml" specified in default
current-sensing-1  | CRITICAL:config:Config File Not Found - unable to load config file "./config/module_config.toml" specified by default.
current-sensing-1  | INFO:config:Loaded config file "./config/user_config.toml" specified in default
current-sensing-1  | CRITICAL:config:Config File Not Found - unable to load config file "./config/module_config.toml" specified by default.
current-sensing-1  | INFO:config:Loaded config file "./config/user_config.toml" specified in default
current-sensing-1  | CRITICAL:config:Config File Not Found - unable to load config file "./config/module_config.toml" specified by default.
current-sensing-1  | INFO:config:Loaded config file "./config/user_config.toml" specified in default
current-sensing-1  | CRITICAL:config:Config File Not Found - unable to load config file "./config/module_config.toml" specified by default.
current-sensing-1  | INFO:config:Loaded config file "./config/user_config.toml" specified in default
current-sensing-1  | CRITICAL:config:Config File Not Found - unable to load config file "./config/module_config.toml" specified by default.
```

**Comment by Greg-Hawkridge** [comment]
@tobyaharris should be ready now

**Review by tobyaharris — CHANGES_REQUESTED** [review]
dummy changes plz

**Review by tobyaharris — CHANGES_REQUESTED** [review]
Dummy further changes!

**Review by tobyaharris — APPROVED** [review]

**Pull request merged**
